name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Sync Data 2
      run: ./scripts/sync.sh && wc -l ./src/data/summer-schools.csv
    - name: Print Data 2
      run: cat ./src/data/summer-schools.csv
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
         deploy-branch: gh-pages
